### ISSUE TITLE
Can't call datareader as an app? Install option not working...

### ISSUE THREAD

**Issue by sv3t0sl4v** [Altinity/clickhouse-mysql-data-reader#191]
Hi!

It seems I can't run data reader as a server.

`which clickhouse-mysql`
/usr/local/bin/clickhouse-mysql

`/usr/local/bin/clickhouse-mysql --install`
Traceback (most recent call last):
  File "/usr/local/bin/clickhouse-mysql", line 5, in <module>
    from clickhouse_mysql import main
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_mysql/__init__.py", line 4, in <module>
    from .main import Main
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_mysql/main.py", line 21, in <module>
    from clickhouse_mysql.config import Config
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_mysql/config.py", line 4, in <module>
    from clickhouse_mysql.reader.mysqlreader import MySQLReader
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_mysql/reader/mysqlreader.py", line 8, in <module>
    from pymysqlreplication import BinLogStreamReader
  File "/usr/local/lib/python3.8/dist-packages/pymysqlreplication/__init__.py", line 23, in <module>
    from .binlogstream import BinLogStreamReader
  File "/usr/local/lib/python3.8/dist-packages/pymysqlreplication/binlogstream.py", line 9, in <module>
    from pymysql.util import int2byte
ModuleNotFoundError: No module named 'pymysql.util'

Ideas how to solve? OS - Ubuntu 20.04.2, MySQL 5.7. 
Thanks!

**Comment by sv3t0sl4v** [comment]
Solved by installing older version of pymysql with `pip3 install "PyMySQL==0.9.3"`
