### ISSUE TITLE
error occurs  while connecting source mysql instance without default port

### ISSUE THREAD

**Issue by linyue515** [Altinity/clickhouse-mysql-data-reader#84]
When I connection to source mysql instance ,which's port is 30307 .   But mysql instance port is 3306 , no error.  I think the parameter --src-port=30307  is invalid .
``
./bin/pypy ./bin/clickhouse-mysql --log-file=/dev/null --src-host=10.105.2.121  --src-user=reader --src-password=qwerty --src-port=30307 --table-templates --src-schemas=linyue --src-tables=t
=============
Traceback (most recent call last):
  File "/opt/pypy3-v5.10.0-linux64/site-packages/clickhouse_mysql/tableprocessor.py", line 82, in connect
    cursorclass=self.cursorclass,
  File "/opt/pypy3-v5.10.0-linux64/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/opt/pypy3-v5.10.0-linux64/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on '10.105.2.121' (111)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pypy3-v5.10.0-linux64/site-packages/clickhouse_mysql/main.py", line 40, in run
    templates = self.config.table_builder().templates(self.config.is_table_templates_json())
  File "/opt/pypy3-v5.10.0-linux64/site-packages/clickhouse_mysql/tablebuilder.py", line 23, in templates
    templates[db][table] = self.create_table_description(db=db, table=table, json=json)
  File "/opt/pypy3-v5.10.0-linux64/site-packages/clickhouse_mysql/tablebuilder.py", line 35, in create_table_description
    columns_description = self.create_table_columns_description(db=db, table=table)
  File "/opt/pypy3-v5.10.0-linux64/site-packages/clickhouse_mysql/tablebuilder.py", line 85, in create_table_columns_description
    self.connect(db=db)
  File "/opt/pypy3-v5.10.0-linux64/site-packages/clickhouse_mysql/tableprocessor.py", line 90, in connect
    db
Exception: Can not connect to the database host=10.105.2.121 user=reader password=qwerty db=linyue
=============
Can not connect to the database host=10.105.2.121 user=reader password=qwerty db=linyue
 ``

**Comment by linyue515** [comment]
Another issue , this tool  can not parse binlog format 5.7 。

**Comment by linyue515** [comment]
clickhouse_mysql/tableprocessor.py  line82

**Comment by linyue515** [comment]
I have fixed  it
